import {Button,Form,FormItem,Input,Message,Radio,RadioGroup,PageHeader,Container,Header,Aside,Main,Avatar,Dropdown,DropdownItem,DropdownMenu,Drawer,Image,Row,Col,Tooltip,Tag,Menu,MenuItem,MenuItemGroup,Submenu,Link,Dialog} from 'element-ui'
import Vue from 'vue'

Vue.prototype.$message=Message
Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(PageHeader)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Avatar)
Vue.use(Dropdown)
Vue.use(DropdownItem)
Vue.use(DropdownMenu)
Vue.use(Drawer)
Vue.use(Image)
Vue.use(Row)
Vue.use(Col)
Vue.use(Tooltip)
Vue.use(Tag)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Submenu)
Vue.use(Link)
Vue.use(Dialog)